# Site
name: 'while True: learn()'
description: 'A blog about data, learning, games, and learning through games.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blog'
url: 'https://jerrylinew.github.io'
disqus: 'whiletruelearn'
email: 'jerrylinew@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jerry:
      name:           Jerry
      site:           https://whiletruelearn.me
      avatar:         assets/images/avatar.png
      bio:            "Jerry is a software engineer who transforms food into code. When not hacking away or getting lost in data,
                       he likes to play board/video games, teach math & computer science, and play badminton."
      email:          jerrylinew@gmail.com

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jerry
      avatar: /assets/images/avatar.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]